### ISSUE TITLE
Use the dotenv library

### ISSUE THREAD

**Issue by p1-dta** [AIDRI/rl_rps#1]
I suggest the library `dotenv`. With an ignored file `.env`, you can work without any code modification. The goal is to improve those lines:

master/discord_adaptator.py > line 54
```python
52 if __name__ == "__main__":
53     bot = Bot()
54     bot.run("YOUR TOKEN")
55     print(self.input)
```

Here is how it work:
```python
from dotenv import load_dotenv

if __name__ == "__main__"
    load_dotenv()
    TOKEN = os.getenv('DISCORD_TOKEN')
    bot = Bot()
    bot.run(TOKEN)
```
with the `.env` file:
```
DISCORD_TOKEN=<your token>
```

**Comment by AIDRI** [comment]
thank you for this issue, I m going to modify my script with this part of the script

**Comment by AIDRI** [comment]
done
